-- Create the User table
create table if not exists public."User" (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  "Name" text,
  "Username" text,
  "Password" text,
  "Email" text,
  "Mobile No" text,
  "Age" text,
  "Height" text,
  "Weight" text,
  "Client's Image (Attachment)" text,
  "Spreadsheet ID" text,
  "Worksheet ID (Cloth Log)" text,
  "Folder ID" text,
  "Gender" text
);

-- If table already exists, add the column safely
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='Gender') THEN
        ALTER TABLE public."User" ADD COLUMN "Gender" text;
    END IF;
END $$;

-- Enable Row Level Security (RLS) recommended but optional for internal tool
alter table public."User" enable row level security;

-- Create a policy to allow anyone to read/write (since we are doing 'admin' via frontend backdoor)
-- WARNING: In a real prod app, you'd want authenticated policies.
-- Drop policy if it exists to avoid error on re-run
drop policy if exists "Enable read access for all users" on public."User";

create policy "Enable read access for all users"
on public."User"
as permissive
for all
to public
using (true)
with check (true);

-- Create the Storage Bucket for images
insert into storage.buckets (id, name, public)
values ('user-images', 'user-images', true)
on conflict (id) do nothing;

-- Allow public access to upload/view images in this bucket
-- Drop policy if it exists
drop policy if exists "Public Access" on storage.objects;

create policy "Public Access"
on storage.objects for all
using ( bucket_id = 'user-images' )
with check ( bucket_id = 'user-images' );

-- Create History Table for Cloud Sync
create table if not exists public.try_on_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id bigint references public."User"(id),
  result_image text,
  items_used jsonb
);

-- RLS for History
alter table public.try_on_history enable row level security;

-- Policy: Users can only see their own history
drop policy if exists "Users can see own history" on public.try_on_history;
create policy "Users can see own history"
on public.try_on_history
for select
using ( true ); 
-- NOTE: We are using a custom 'User' table with BigInt IDs, so strict Supabase Auth UUID checks don't apply directly here.
-- The frontend filters data by user_id.

-- Policy: Anyone can insert (since we are doing client-side insert for this demo)
drop policy if exists "Users can insert history" on public.try_on_history;
create policy "Users can insert history"
on public.try_on_history
for insert
with check ( true ); 

-- Policy: Users can delete their own history
drop policy if exists "Users can delete own history" on public.try_on_history;
create policy "Users can delete own history"
on public.try_on_history
for delete
using ( true );
